### PR TITLE
fix ethan's mistakes

### LINKED ISSUE #1: Incompetence
Who freddy

### PR DESCRIPTION
**Pull request by alyssa-blair**
update the name to Fretty and minor changes to the script for an optimal building experience.

### CODE REVIEW

**Review by wrighted — COMMENTED** [review]
Seems miraculously you didn't miss any renames.

To be clear, this does not fix the C# -> React problem?

**Comment by alyssa-blair** [comment]
Master ctrl f'er over here what can I say. I think I commented out a line that was causing the backend boot to fail, but doesn't fix the other problems.

**Comment by alyssa-blair** [comment]
Added in the fix for cors cuz you take 400 years to approve my pr :p

**Comment by wrighted** [comment]
Not yet working in docker, waiting for fix.

**Review by wrighted — APPROVED** [review]
Works for me now.

**Pull request merged**
